package com.example.telemaven.bot.constans;

public interface Actions {
    String PAIR_ACTION = "pair";
    String MONDAY_PAIR_ACTION = "MONDAY_PAIR";
    String TUESDAY_PAIR_ACTION = "TUESDAY_PAIR";
    String WEDNESDAY_PAIR_ACTION = "WEDNESDAY_PAIR";
    String THURSDAY_PAIR_ACTION = "THURSDAY_PAIR";
    String FRIDAY_PAIR_ACTION = "FRIDAY_PAIR";
    String UNPAIR_ACTION = "unpair";
    String MONDAY_UNPAIR_ACTION = "MONDAY_UNPAIR";
    String TUESDAY_UNPAIR_ACTION = "TUESDAY_UNPAIR";
    String WEDNESDAY_UNPAIR_ACTION = "WEDNESDAY_UNPAIR";
    String THURSDAY_UNPAIR_ACTION = "THURSDAY_UNPAIR";
    String FRIDAY_UNPAIR_ACTION = "FRIDAY_UNPAIR";
    String BACK_ACTION = "back";
    String HOMEWORK_ACTION = "HOMEWORK_ACTION";
    String TIMETABLE_ACTION = "TIMETABLE";
    String WEEK_ACTION = "WEEK";
    String NOTIFICATION_ACTION = "NOTIFICATION";

    String REGISTER_ACTION = "REGISTER";
    String UNREGISTER_ACTION = "UNREGISTER";

    String MODULE_ACTION = "MODULE";
    String SESSION_ACTION = "SESSION";
    String EXAM_ACTION = "EXAM";
    String CREDIT_ACTION = "CREDIT";


}
